config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :transactions
  resources :products
  resources :storages
  resources :productions
  resources :finances do
    collection do 
      get :export_csv
    end
  end
end

app/models/finance.rb
class Finance < ApplicationRecord
  belongs_to :user
  
  validates :description, presence: true
  validates :transaction_type, presence: true
  validates :amount, presence: true
  enum transaction_type: [ :entrada, :saida ]
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: %i[ show edit update destroy ]
  include Exportable

  def index
    params[:q] ||= {}
    if params[:q][:created_at_lteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_lteq].to_date.end_of_day
    end

    @q = current_user.finances.ransack(params[:q])
    @finances = @q.result.page(params[:page]).order(created_at: :desc)
    @total_amount = total_balance
  end

  def show
  end

  def new
    @finance = current_user.finances.new
    prepare_form
  end

  def edit
    prepare_form
  end

  def create
    @finance = current_user.finances.new(finance_params)
    if @finance.save
      redirect_to finances_path, notice: "Finance was successfully created."
    else  
      prepare_form
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @finance.update(finance_params)
      redirect_to finance_url(@finance), notice: "Finance was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @finance.destroy

    respond_to do |format|
      format.html { redirect_to finances_url, notice: "Finance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_finance
      @finance = current_user.finances.find(params[:id])
    end

    def finance_params
      params.require(:finance).permit(:transaction_type, :description, :amount)
    end

    def prepare_form
      @finances = current_user.finances.transaction_types.keys.map{ |key| [key.humanize, key] }
    end

    def total_balance
      total_money = current_user.finances.entrada.sum(:amount)
      waste = current_user.finances.saida.sum(:amount)
      balance = total_money - waste
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_form.html.erb
<%= turbo_frame_tag 'new_finance_component' do %>
  <div class="w-full items-center bg-white rounded-lg shadow-lg p-2">
    <%= form_with(model: @finance, data: {turbo_frame: 'tabela-finance'}) do |f| %>
      <% if finance.errors.any? %>
        <div class="bg-red-400 p-2 rounded-lg mb-2">
          <% finance.errors.each do |error|%>
            <div class="text-white">
              <span><%= error.full_message %></span>
            </div>
          <% end %>
        </div>
      <% end %>
    <div class="space-y-2 md:flex md:items-center md:space-x-2 md:space-y-0">
      <div>
        <%= f.text_field :description, class: "input ", placeholder: "Descrição" %>
      </div>
      <div>
        <%= f.text_field :amount, class: "input ", placeholder: "Valor" %>
      </div>
      <div>
        <%= f.select :transaction_type, @finances, { include_blank: "Selecione" }, class: "input" %>
      </div >
      <div class="flex space-x-1">
        <%= f.submit "Confirmar", class: "btn-green" %>
        <%= link_to "Voltar", :back, class: "btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/finances/_table.html.erb
<div class="mt-6 overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-white  border-b border-gray-300">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Descrição
                </th>
                <th scope="col" class="px-6 py-3">
                    Tipo
                </th>
                <th scope="col" class="px-6 py-3">
                    Valor
                </th>
                <th scope="col" class="px-6 py-3">
                    Data
                </th>
            </tr>
        </thead>
        <tbody>
        <% @finances.each do |finance| %>
          <% if finance.transaction_type === "saida" %>
            <tr class="border-b border-gray-200 text-red-900 bg-red-50">
                <th scope="row" class="px-6 py-4 font-medium  whitespace-nowrap ">
                  <%= finance.description %>
                </th>
                <td class="px-6 py-4">  
                  <%= finance.transaction_type %>
                </td>
                <td class="px-6 py-4">
                  - <%= number_to_currency(finance.amount, unit: 'R$', separator: ',', delimiter: '.', precision: 2) %>
                </td>
                <td class="px-6 py-4">
                  <%= finance.created_at.strftime("%d/%m/%Y") %>
                </td>
            </tr>
          <% else %>
            <tr class="border-b border-gray-200 text-green-900 bg-green-50">
                <th scope="row" class="px-6 py-4 font-medium  whitespace-nowrap ">
                  <%= finance.description %>
                </th>
                <td class="px-6 py-4">
                  <%= finance.transaction_type %>
                </td>
                <td class="px-6 py-4">
                  + <%= number_to_currency(finance.amount, unit: 'R$', separator: ',', delimiter: '.', precision: 2) %>
                </td>
                <td class="px-6 py-4">
                  <%= finance.created_at.strftime("%d/%m/%Y") %>
                </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
    </table>
</div>

app/views/finances/index.html.erb
<div class="bg-white w-full h-full shadow-lg rounded-lg">
  <div class="px-2 font-bold">
    <h1 class="text-3xl py-2">Controle de Caixa</h1>
  </div>
</div>

<%= turbo_frame_tag 'tabela-finance' do %>
  <div class="flex justify-end items-center space-x-2">
    <div class="mt-5">
      <div>
        <%= link_to "Exportar", export_csv_finances_path, class: "btn-primary", data: {turbo: false} %>
      </div>
    </div>
    <div class="bg-white rounded-lg shadow-lg mt-5">
      <p class="text-lg p-2">Total:
        <%= number_to_currency(@total_amount, unit: 'R$',
        separator: ',', delimiter: '.', precision: 2) %>
      </p>
    </div>
  </div>
  <div class="mx-auto justify-end flex mt-6">
    <%= turbo_frame_tag 'new_finance_component', class: "space-x-2" do %>
      <%= link_to new_finance_path, id:'finance_link', class:"btn-green" do %>
        + Movimentação
      <% end %>
    <% end %>
  </div>
  <div class="md:flex md:justify-between items-center mt-12">
    <div class="text-center">
      <%= paginate @finances %>
    </div>
    <%= search_form_for @q, url: finances_path do |f| %>
      <div date-rangepicker datepicker-format="dd/mm/yyyy" class="flex items-center">
        <span class="mx-4 text-gray-500">Filtrar de</span>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
              </svg>
          </div>
          <%= f.search_field :created_at_gteq, class: 'date-input' %>
        </div>
        <span class="mx-4 text-gray-500">até</span>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
              <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
              </svg>
          </div>
          <%= f.search_field :created_at_lteq, class: 'date-input' %>
        </div>
        <div class="ml-2">
          <%= f.submit "Filtrar", class: "btn-primary", data: { turbo_frame: 'tabela-finance'} %>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <%= render 'table'%>
  </div>
<% end %>

app/views/finances/new.html.erb
<%= render 'form', {finance: @finance } %>