config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :transactions
  resources :products
  resources :storages
  resources :productions
  resources :finances do
    collection do 
      get :export_csv
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @productions = Production.joins(:product).where(date_time: week_range, product: {user: current_user}).limit(5)
    @transactions = Transaction.joins(:product).where(date_time: week_range, product: {user: current_user}).limit(5)
  end

  def week_range
    (start_week = Time.current.beginning_of_week...end_of_week = Time.current.end_of_week)
  end
end

app/views/home/_tables.html.erb
<div class="md:grid md:grid-cols-2 md:justify-center md:space-x-12">
  <div>
    <div class="mt-5 md:px-4 text-center md:text-start flex items-center justify-between">
      <h1 class="font-semibold text-3xl">Vendas da semana</h1>
      <%= link_to "ver mais", transactions_path, data: { turbo: false }, class: "text-blue-700 font-bold hover:text-blue-800" %>
    </div>
    <div class="mt-6 overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Produto
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Quantidade (Kgs)
                    </th>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Valor
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Data
                    </th>
                </tr>
            </thead>
            <tbody>
              <% @transactions.each do |transaction| %>
                <tr class="border-b border-gray-200 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
                      <%= transaction.product.name %>
                    </th>
                    <td class="px-6 py-4">
                      <%= transaction.quantity %>
                    </td>
                    <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                      <%= transaction.amount %>
                    </td>
                    <td class="px-6 py-4 ">
                      <%= transaction.date_time.strftime("%d/%m/%Y") %>
                    </td>
                </tr>
              <% end %>
            </tbody>
        </table>
    </div>
  </div>
  <div>
    <div class="mt-5 md:px-4 text-center md:text-start flex items-center justify-between">
      <h1 class="font-semibold text-3xl">Produção da semana</h1>
      <%= link_to "ver mais", productions_path, data: { turbo: false }, class: "text-blue-700 hover:text-blue-800 font-bold" %>
    </div>
    <div class="mt-6 overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Produto
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Quantidade (Kgs)
                    </th>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Data
                    </th>
                </tr>
            </thead>
            <tbody>
              <% @productions.each do |production| %>
                <tr class="border-b border-gray-200 dark:border-gray-700">
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
                    <%= production.product.name %>
                  </th>
                  <td class="px-6 py-4">
                    <%= production.quantity %>
                  </td>
                  <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                      <%= production.date_time.strftime("%d/%m/%Y") %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex justify-center">
  <div class="px-2 font-bold text-center w-1/2 bg-white rounded-lg mb-12">
    <p class="text-3xl py-4">Painel de Controle</p>
  </div>
</div>
<%= turbo_frame_tag 'tabelas' do %>
  <div class="mx-auto justify-end flex">
    <%= turbo_frame_tag 'new_record_component', class: "space-x-2" do %>
      <%= link_to new_transaction_path, id:'sale_link', class:"btn-green" do %>
        + Venda
      <% end %>
      <%= link_to new_production_path, id:'production_link', class:"btn-green" do %>
        + Produção
      <% end %>
    <% end %>
  </div>
  <%= turbo_stream_from "transactions_charts_channel#{current_user.id}" %>
  <%= turbo_stream_from "productions_charts_channel#{current_user.id}" %>

  <div class="md:flex justify-center space-x-auto md:space-x-2 md:space-y-0 space-y-2 items-center mt-6">
    <%= render 'home/charts/days/days'%>
    <%= render 'home/charts/productions/productions'%>
    <%= render 'home/charts/transactions/transactions'%>
  </div>
  <div class="px-4">
    <%= render 'tables' %>
  </div>
<% end %>