config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :transactions
  resources :products
  resources :storages
  resources :productions
  resources :finances do
    collection do 
      get :export_csv
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :productions

  validates :name, presence: true

  def sum_storage
   product_quantity = Product.left_joins(:productions).select("products.*, sum(productions.quantity) as total").group(:id)
   total_product = product_quantity.total
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = current_user.products.all.order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @product = current_user.products.new
  end

  def edit
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to products_path, notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        redirect_to products_path, notice: "Product was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = current_user.products.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= turbo_frame_tag 'new_product_component' do %>
  <div class="w-full items-center bg-white rounded-lg shadow-lg p-2">
    <%= form_with(model: @product, data: {turbo_frame: 'tabela'}) do |f| %>
      <% if product.errors.any? %>
        <div class="bg-red-400 p-2 rounded-lg mb-2">
          <% product.errors.each do |error|%>
            <div class="text-white">
              <span><%= error.full_message %></span>
            </div>
          <% end %>
        </div>
      <% end %>
    <div class="space-y-2 md:flex md:items-center md:space-x-2 md:space-y-0">
      <div>
        <%= f.text_field :name, class: "input ", placeholder: "Nome" %>
      </div >
      <div class="flex space-x-1">
        <%= f.submit "Confirmar", class: "btn-green" %>
        <%= link_to "Voltar", :back, class: "btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/products/_table.html.erb
<div class="mt-6 overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
          Produto
        </th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr class="border-b border-gray-200 dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
            <%= product.name %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/index.html.erb
<div class="bg-white w-full h-full shadow-lg rounded-lg">
  <div class="px-2 font-bold">
    <h1 class="text-3xl py-2">Produtos</h1>
  </div>
</div>
<%= turbo_frame_tag 'tabela' do %>
  <div class="my-2 flex justify-end mt-5">
    <%= turbo_frame_tag 'new_product_component', class: "space-x-2" do %>
      <%= link_to new_product_path, id:'product_link', class:"btn-green" do %>
        + Produto
      <% end %>
    <% end %>
  </div>
  <div>
    <div>
      <%= render 'table'%>
    </div>
<% end %> 
</div>

app/views/products/new.html.erb
<%= render 'form', {product: @product } %>